### ISSUE TITLE
Request to publish a stable version of `diox`

### ISSUE THREAD

**Issue by mdddj** [cfug/diox#59]
### Request Statement

![image](https://user-images.githubusercontent.com/29020213/210690998-ba957975-c438-4caf-8072-9fc64168991a.png)

第三方插件依赖了diox dev版本,上传发布的时候有警告

### Solution Brainstorm

希望能发布到正式版

**Comment by AlexV525** [comment]
The first stable release has been published. https://github.com/cfug/diox/releases/tag/v5.0.0
