### ISSUE TITLE
The statusCode in the exception capture response is null

### ISSUE THREAD

**Issue by mdddj** [cfug/diox#63]
### Package

diox

### Version

5.0.0-dev.3

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2 Preview)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
[✓] VS Code (version 1.74.2)
[✓] Proxy Configuration
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

### Dart Version

2.18.6

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/29020213/212005068-3bd4dae0-f6a7-4334-82a3-504a28658fc3.png)

1. Request an API
example: https://xxxxxxx.cn/rest/V1/mstore/orders
2. Return 401 status code
3. DioError.response.statusCode is null

![image](https://user-images.githubusercontent.com/29020213/212005230-79fa3a02-fc2e-43a9-84df-61d6c2bae9cd.png)

### Expected Result

e.response?.statusCode   return   `401` code

### Actual Result

e.response?.statusCode   return  null

**Comment by mdddj** [comment]
不能百分百复现,暂时关闭

**Comment by mdddj** [comment]
![image](https://user-images.githubusercontent.com/29020213/212012865-b2c3a2eb-841b-4d5d-aeff-1d5b569aa64a.png)

401 状态码  response 不应该为空

**Comment by AlexV525** [comment]
![image](https://user-images.githubusercontent.com/15884415/212230185-c23d41d8-2a66-4ef1-88cc-c8130aa66eb0.png)

**Comment by mdddj** [comment]
不确定是不是和后端有关系, 现在可以百分百复现,    接口后端是php写的, 我不会,也没有服务器来部署api接口, 换回dio是没有这个问题的

**Comment by AlexV525** [comment]
提供有效的复现接口。

**Comment by mdddj** [comment]
接口在公司局域网内才能访问, 我在使用其他方法解决了这个
```dart
            int? errCode = error.response?.statusCode;

            final msg = error.message;
            if (msg?.contains('401') == true) {
              return UnauthorisedException(401, msg ?? "Permission denied");
            }
            if (msg?.contains('400') == true) {
              return BadRequestException(400, msg ?? "Request syntax error");
            }
```
暂时关闭
