### ISSUE TITLE
More documention on using this as a replacement/fork of dio

### ISSUE THREAD

**Issue by josh-burton** [cfug/diox#67]
### Request Statement

The readme says: `To use diox as a dio's fork, use dependency_overrides in your pubspec.yaml: ...`

Can you add more documentation around the dio branch, how it differs from the main branch, when it is updated etc?

Is it intended as a version of diox that is compatible as a dio replacement?

**Comment by AlexV525** [comment]
Indeed. I'll try to explain more in the docs. Thanks for mentioning it.
